# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20130607201751) do

  create_table "agreements", :force => true do |t|
    t.string   "name"
    t.string   "phone"
    t.string   "email"
    t.string   "box"
    t.string   "title"
    t.date     "perfstart"
    t.date     "perfend"
    t.date     "duedate"
    t.string   "financer"
    t.string   "employee"
    t.datetime "created_at",                                 :null => false
    t.datetime "updated_at",                                 :null => false
    t.string   "lost0"
    t.decimal  "cost0",      :precision => 30, :scale => 10
    t.string   "lost1"
    t.decimal  "cost1",      :precision => 30, :scale => 10
    t.string   "lost2"
    t.decimal  "cost2",      :precision => 30, :scale => 10
    t.string   "lost3"
    t.decimal  "cost3",      :precision => 30, :scale => 10
    t.string   "lost4"
    t.decimal  "cost4",      :precision => 30, :scale => 10
    t.string   "dry0"
    t.string   "gar0"
    t.string   "dry1"
    t.string   "gar1"
    t.string   "dry2"
    t.string   "gar2"
    t.string   "dry3"
    t.string   "gar3"
    t.string   "dry4"
    t.string   "gar4"
    t.string   "dry5"
    t.string   "gar5"
    t.string   "dry6"
    t.string   "gar6"
    t.string   "dry7"
    t.string   "gar7"
    t.string   "dry8"
    t.string   "gar8"
    t.string   "dry9"
    t.string   "gar9"
    t.integer  "gar_sent"
    t.integer  "gar_back"
    t.string   "item00"
    t.string   "wd00"
    t.boolean  "back00"
    t.text     "photo00"
    t.string   "item01"
    t.string   "wd01"
    t.boolean  "back01"
    t.text     "photo01"
    t.string   "item02"
    t.string   "wd02"
    t.boolean  "back02"
    t.text     "photo02"
    t.string   "item03"
    t.string   "wd03"
    t.boolean  "back03"
    t.text     "photo03"
    t.string   "item04"
    t.string   "wd04"
    t.boolean  "back04"
    t.text     "photo04"
    t.string   "item05"
    t.string   "wd05"
    t.boolean  "back05"
    t.text     "photo05"
    t.string   "item06"
    t.string   "wd06"
    t.boolean  "back06"
    t.text     "photo06"
    t.string   "item07"
    t.string   "wd07"
    t.boolean  "back07"
    t.text     "photo07"
    t.string   "item08"
    t.string   "wd08"
    t.boolean  "back08"
    t.text     "photo08"
    t.string   "item09"
    t.string   "wd09"
    t.boolean  "back09"
    t.text     "photo09"
    t.string   "item10"
    t.string   "wd10"
    t.boolean  "back10"
    t.text     "photo10"
    t.string   "item11"
    t.string   "wd11"
    t.boolean  "back11"
    t.text     "photo11"
    t.string   "item12"
    t.string   "wd12"
    t.boolean  "back12"
    t.text     "photo12"
    t.string   "item13"
    t.string   "wd13"
    t.boolean  "back13"
    t.text     "photo13"
    t.string   "item14"
    t.string   "wd14"
    t.boolean  "back14"
    t.text     "photo14"
    t.string   "item15"
    t.string   "wd15"
    t.boolean  "back15"
    t.text     "photo15"
    t.string   "item16"
    t.string   "wd16"
    t.boolean  "back16"
    t.text     "photo16"
    t.string   "item17"
    t.string   "wd17"
    t.boolean  "back17"
    t.text     "photo17"
    t.string   "item18"
    t.string   "wd18"
    t.boolean  "back18"
    t.text     "photo18"
    t.string   "item19"
    t.string   "wd19"
    t.boolean  "back19"
    t.text     "photo19"
    t.string   "item20"
    t.string   "wd20"
    t.boolean  "back20"
    t.text     "photo20"
    t.string   "item21"
    t.string   "wd21"
    t.boolean  "back21"
    t.text     "photo21"
    t.string   "item22"
    t.string   "wd22"
    t.boolean  "back22"
    t.text     "photo22"
    t.string   "item23"
    t.string   "wd23"
    t.boolean  "back23"
    t.text     "photo23"
    t.string   "item24"
    t.string   "wd24"
    t.boolean  "back24"
    t.text     "photo24"
    t.string   "item25"
    t.string   "wd25"
    t.boolean  "back25"
    t.text     "photo25"
    t.string   "item26"
    t.string   "wd26"
    t.boolean  "back26"
    t.text     "photo26"
    t.string   "item27"
    t.string   "wd27"
    t.boolean  "back27"
    t.text     "photo27"
    t.string   "item28"
    t.string   "wd28"
    t.boolean  "back28"
    t.text     "photo28"
    t.string   "item29"
    t.string   "wd29"
    t.boolean  "back29"
    t.text     "photo29"
    t.string   "item30"
    t.string   "wd30"
    t.boolean  "back30"
    t.text     "photo30"
    t.string   "item31"
    t.string   "wd31"
    t.boolean  "back31"
    t.text     "photo31"
    t.string   "item32"
    t.string   "wd32"
    t.boolean  "back32"
    t.text     "photo32"
    t.string   "item33"
    t.string   "wd33"
    t.boolean  "back33"
    t.text     "photo33"
    t.string   "item34"
    t.string   "wd34"
    t.boolean  "back34"
    t.text     "photo34"
    t.string   "item35"
    t.string   "wd35"
    t.boolean  "back35"
    t.text     "photo35"
    t.string   "item36"
    t.string   "wd36"
    t.boolean  "back36"
    t.text     "photo36"
    t.string   "item37"
    t.string   "wd37"
    t.boolean  "back37"
    t.text     "photo37"
    t.string   "item38"
    t.string   "wd38"
    t.boolean  "back38"
    t.text     "photo38"
    t.string   "item39"
    t.string   "wd39"
    t.boolean  "back39"
    t.text     "photo39"
    t.string   "item40"
    t.string   "wd40"
    t.boolean  "back40"
    t.text     "photo40"
    t.string   "item41"
    t.string   "wd41"
    t.boolean  "back41"
    t.text     "photo41"
    t.string   "item42"
    t.string   "wd42"
    t.boolean  "back42"
    t.text     "photo42"
    t.string   "item43"
    t.string   "wd43"
    t.boolean  "back43"
    t.text     "photo43"
    t.string   "item44"
    t.string   "wd44"
    t.boolean  "back44"
    t.text     "photo44"
    t.string   "item45"
    t.string   "wd45"
    t.boolean  "back45"
    t.text     "photo45"
    t.string   "item46"
    t.string   "wd46"
    t.boolean  "back46"
    t.text     "photo46"
    t.string   "item47"
    t.string   "wd47"
    t.boolean  "back47"
    t.text     "photo47"
    t.string   "item48"
    t.string   "wd48"
    t.boolean  "back48"
    t.text     "photo48"
    t.string   "item49"
    t.string   "wd49"
    t.boolean  "back49"
    t.text     "photo49"
  end

  create_table "costumes", :force => true do |t|
    t.string   "description"
    t.string   "clean"
    t.boolean  "back",         :default => false
    t.string   "photo"
    t.integer  "agreement_id"
    t.datetime "created_at",                      :null => false
    t.datetime "updated_at",                      :null => false
  end

  add_index "costumes", ["agreement_id"], :name => "index_costumes_on_agreement_id"

end
